name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0, v2.1.3)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: hypolas/ecsazrlc
          tags: |
            # Version tags (e.g., v1.2.3 -> 1.2.3)
            type=semver,pattern={{version}}
            # Major.minor tags (e.g., v1.2.3 -> 1.2)
            type=semver,pattern={{major}}.{{minor}}
            # Major tags (e.g., v1.2.3 -> 1)
            type=semver,pattern={{major}}
            # Latest tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # Multi-platform build
          # Supported: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6, linux/386
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Build arguments (optional)
          build-args: |
            GO_VERSION=1.25.1

      # - name: Update Docker Hub description
      #   uses: peter-evans/dockerhub-description@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: hypolas/ecsazrlc
      #     short-description: ${{ github.event.repository.description }}
      #     readme-filepath: ./README.md
