name: Renovate

on:
  # Run on schedule (every day at 23:00 UTC / 00:00 CET / 01:00 CEST)
  schedule:
    - cron: '00 23 * * *'

  # Manual trigger
  workflow_dispatch:

  # Run on push to renovate config
  push:
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
